LLM:
  description: Basic iskra model for testing
  model_name: iskra-8b
  model_path: /home/vapa/projects/iskra/models/llms/iskra-8b
  system_prompt: You have access to a Spotify player. If a user asks you to play some music, respond only with the name of the song you were asked to play.
